config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
  
  resources :users, only: [:index, :show]  do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end  
  end

  # api endpoints routes
  namespace :api do
    namespace :v1 do
      resources :users , only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    return unless user.present?

    can :manage, Post, author_id: user.id
    can :destroy, Comment, author_id: user.id
    can :create, Comment
    can :read, :all
    return unless user.is? :admin

    can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'

  after_save :update_comments_counter

  after_destroy :decrement_comments_counter

  private

  def decrement_comments_counter
    post.decrement!(:comments_counter)
  end

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  after_save :update_post_counter

  after_destroy :decrement_posts_counter

  private

  def decrement_posts_counter
    author.decrement!(:posts_counter)
  end

  def update_post_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy_async
  has_many :likes, foreign_key: 'author_id', dependent: :destroy_async
  has_many :comments, foreign_key: 'author_id', dependent: :destroy_async

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  ROLES = %i[admin default].freeze
  def is?(requested_role)
    role == requested_role.to_s
  end

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ActionController::API
  respond_to :json
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::V1::ApplicationController
  def index
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
    @comments = @post.comments.all
    render json: @comments, status: :ok
  end

  def create
    @comment = Comment.create(
      text: comment_params[:text],
      author_id: params[:user_id],
      post_id: params[:post_id]
    )

    render json: @comment, status: :created
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
    render json: @posts, status: :ok
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(_resource)
    user_url(current_user)
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email bio photo password confirm_password])
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[name password])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[name email bio photo password current_password])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = params[:post_id]

    if @comment.save
      redirect_to user_post_path(params[:user_id], params[:post_id])
      flash[:success] = 'Comment added successfully'
    else
      @user = Post.find(params[:user_id])
      @post = Post.find(params[:post_id])
      flash.now[:error] = 'Error: Comment could not be deleted'
      redirect_to user_post_path(@user, @post)
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    if comment.destroy
      redirect_to user_post_path
    else
      flash.now[:error] = 'Error: Comment could not be deleted'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new
    @like.post_id = params[:post_id]

    return unless @like.save

    redirect_to user_post_path(@like.author, @like.post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(**post_params, author_id: current_user.id)
    @user = current_user

    if @post.save
      redirect_to user_post_path(@user, @post), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      redirect_to user_posts_path, notice: 'Post was successfully destroyed.'
    else
      flash.now[:error] = 'Error: Post could not be deleted'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all.order('id ASC')
  end

  def show
    @user = User.includes(:posts).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h5> Create a new Comment:</h5>
<%= form_with model: @comment, url: user_post_comments_url , method: :post do |form| %>
   <div class="form-group">
    <%= form.label :text , "Text" %>
    <%= form.text_area :text , required: true %>
   </div> 
    <%= form.submit "Post Comment" %>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <title>EasyBlogs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'shared/header'%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/posts/index.html.erb
<section class= mt-2>
  <div class='container grid'>
    <%= render partial: "shared/user", locals: { user: @user } %>
    <div>
      <%= link_to 'Create a new Post' , new_user_post_path %>
    </div>
    <% @posts.each do |post| %>
      <h4><%= link_to post.title, user_post_path(@user, post) %></h4>
      <p><%= post.text %></p>
      <p>
        <small>Comments: <%= post.comments_counter || 0 %>,</small>
        <small>Likes: <%= post.likes_counter || 0 %></small>
      </p>
      <% post.recent_comments.each do |comment| %>
        <div class="row d-flex flex-column border mx-1 mb-2">
          <div class='col p-2'>
            <%= comment.author.name %> : <%= comment.text %>
          </div>
        </div>
      <% end  %>
    <% end %>
  </div>
  <div>
    <button class="button">Pagination</button>
  </div>
</section>

app/views/posts/new.html.erb
<h5> Create a new Post:</h5>
<%= form_with model: @post, url: user_posts_path do |form| %>
   <div class="form-group">
    <%= form.label :title , "Title" %>
    <%= form.text_field :title %>
   </div>
   <div class="form-group">
    <%= form.label :text , "Text" %>
    <%= form.text_area :text , size: '40*40'%>
   </div> 
    <%= form.submit "Post" %>
<% end %>

app/views/posts/show.html.erb
<section class="container">
  <div class="row border mt-3 p-3">
    <div class="d-flex justify-content-between w-100">
      <h5 class=""><%= @post.title %> by <%= @user.name %></h5>
      <p class="text-right">
        <small>Comments: <%= @post.comments_counter || 0 %>,</small>
        <small>Likes: <%= @post.likes_counter || 0 %></small>
      </p>
    </div>
    <p><%= @post.text %></p>
  </div>
  <div classs="d-flex ">
    <%= link_to 'Add a new comment', new_user_post_comment_path(@user, @post) %>
    <%= link_to 'Like', user_post_likes_path(@user, @post),  data: { turbo_method: :post }, class: 'btn btn-primary' %>
    <% if can? :destroy, @post %>
      <%= link_to 'Delete', user_post_path(@user, @post), data: { turbo_method: :delete }, class: 'btn btn-danger' %>
    <% end %>
  </div>
  <div class="border mt-3 p-2">
    <% @post.comments.each do |comment| %>
      <div class="row d-flex align-items-center mx-1 mb-2">
        <div class='col p-2'>
          <%= comment.author.name %> : <%= comment.text %>
        </div>
        <% if can? :destroy, @post %>
          <span>
            <%= link_to 'Delete', user_post_comment_path(@user, @post, comment) , data: { turbo_method: :delete}, class: "py-2 px-4 btn btn-danger text-white" %>
          </span>
        <% end %>
      </div>
    <% end %>
  </div>
</section>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Easy Blogs', root_path , class:"navbar-brand font-weight-bold" %>
  <%# <a class="navbar-brand font-weight-bold" href="#">Easy Blogs</a> %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } , class: 'ml-5 btn btn-primary my-2' %>
        <% else %>
          <%= link_to 'Sign in', new_user_session_path , class: 'ml-5 btn btn-primary my-2' %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_user.html.erb
<div class="row mb-4">
  <div class='col-2'>
    <%= image_tag user.photo , class: 'user-photo' , alt: user.name %>
  </div>
  <div class='col-10 border border-dark font-bold p-2'>
    <%= link_to user.name , user_path(user) , class:'font-weight-bold h5' %>
    <p> Number of Posts: <%= user.posts_counter.nil? ? 0 : user.posts_counter  %> </p>
  </div>
</div>

app/views/users/index.html.erb
<section class= mt-2>
  <h1>List of All Users</h1>
  <div class='container grid'>
    <% @users.each do |user| %>
      <%= render partial: "shared/user", locals: { user: user } %>
    <% end %>
  </div>
</section>

app/views/users/show.html.erb
<section class= mt-2>
  <div class='container grid'>
    <%= render partial: "shared/user", locals: { user: @user } %>
    <div class="row mb-4 border border-dark">
      <div class="col mb-4 pt-4">
        <%= @user.bio %>
      </div>
    </div>
    <% @user.recent_posts.each do |post| %>
      <h4><%= link_to post.title, user_post_path(@user,post) %></h4>
      <p><%= post.text %></p>
      <p>
        <small>Comments: <%= post.comments_counter || 0 %>,</small>
        <small>Likes: <%= post.likes_counter || 0 %></small>
      </p>
    <% end %>
    <button>
      <%= link_to 'See all Posts', user_posts_path(@user) %>
    </button>
  </div>
</section>